package com.smikevon.easy.mbg.domain;

import java.util.Date;

/**
 * Table Name : entrustment
 *
 * @mbg.generated 2018-08-17 13:11:35
 */
public class Entrustment {
    /**
     * ID，委托流水号
     */
    private Long id;

    /**
     * 委托人ID
     */
    private Long userId;

    /**
     * 委托类别（0.委买 1.委卖）
     */
    private Integer applyType;

    /**
     * 交易类别(0.市价, 1.限价)
     */
    private Integer dealType;

    /**
     * 委托交易价格
     */
    private Long price;

    /**
     * 委托交易量
     */
    private Integer entrustAmount;

    /**
     * 成交量
     */
    private Integer dealAmount;

    /**
     * 委托状态（0.交易中 1.交易完成 2.交易取消）
     */
    private Integer status;

    /**
     * 删除标记（0.未删除 1.已删除）
     */
    private Integer isDelete;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 最后更新时间
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.id
     *
     * @return the value of entrustment.id
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.id
     *
     * @param id the value for entrustment.id
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.user_id
     *
     * @return the value of entrustment.user_id
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.user_id
     *
     * @param userId the value for entrustment.user_id
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.apply_type
     *
     * @return the value of entrustment.apply_type
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.apply_type
     *
     * @param applyType the value for entrustment.apply_type
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setApplyType(Integer applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.deal_type
     *
     * @return the value of entrustment.deal_type
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.deal_type
     *
     * @param dealType the value for entrustment.deal_type
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setDealType(Integer dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.price
     *
     * @return the value of entrustment.price
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.price
     *
     * @param price the value for entrustment.price
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.entrust_amount
     *
     * @return the value of entrustment.entrust_amount
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getEntrustAmount() {
        return entrustAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.entrust_amount
     *
     * @param entrustAmount the value for entrustment.entrust_amount
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setEntrustAmount(Integer entrustAmount) {
        this.entrustAmount = entrustAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.deal_amount
     *
     * @return the value of entrustment.deal_amount
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getDealAmount() {
        return dealAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.deal_amount
     *
     * @param dealAmount the value for entrustment.deal_amount
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setDealAmount(Integer dealAmount) {
        this.dealAmount = dealAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.status
     *
     * @return the value of entrustment.status
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.status
     *
     * @param status the value for entrustment.status
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.is_delete
     *
     * @return the value of entrustment.is_delete
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.is_delete
     *
     * @param isDelete the value for entrustment.is_delete
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.create_time
     *
     * @return the value of entrustment.create_time
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.create_time
     *
     * @param createTime the value for entrustment.create_time
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.update_time
     *
     * @return the value of entrustment.update_time
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.update_time
     *
     * @param updateTime the value for entrustment.update_time
     *
     * @mbg.generated 2018-08-17 13:11:35
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}