package com.smikevon.easy.mbg.domain;

import java.util.Date;

public class Entrustment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.user_id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.apply_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer apply_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.deal_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer deal_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.price
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.entrust_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer entrust_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.deal_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer deal_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.status
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.is_delete
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Integer is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.create_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment.update_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.id
     *
     * @return the value of entrustment.id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.id
     *
     * @param id the value for entrustment.id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.user_id
     *
     * @return the value of entrustment.user_id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.user_id
     *
     * @param user_id the value for entrustment.user_id
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.apply_type
     *
     * @return the value of entrustment.apply_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getApply_type() {
        return apply_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.apply_type
     *
     * @param apply_type the value for entrustment.apply_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setApply_type(Integer apply_type) {
        this.apply_type = apply_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.deal_type
     *
     * @return the value of entrustment.deal_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getDeal_type() {
        return deal_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.deal_type
     *
     * @param deal_type the value for entrustment.deal_type
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setDeal_type(Integer deal_type) {
        this.deal_type = deal_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.price
     *
     * @return the value of entrustment.price
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.price
     *
     * @param price the value for entrustment.price
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.entrust_amount
     *
     * @return the value of entrustment.entrust_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getEntrust_amount() {
        return entrust_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.entrust_amount
     *
     * @param entrust_amount the value for entrustment.entrust_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setEntrust_amount(Integer entrust_amount) {
        this.entrust_amount = entrust_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.deal_amount
     *
     * @return the value of entrustment.deal_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getDeal_amount() {
        return deal_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.deal_amount
     *
     * @param deal_amount the value for entrustment.deal_amount
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setDeal_amount(Integer deal_amount) {
        this.deal_amount = deal_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.status
     *
     * @return the value of entrustment.status
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.status
     *
     * @param status the value for entrustment.status
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.is_delete
     *
     * @return the value of entrustment.is_delete
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.is_delete
     *
     * @param is_delete the value for entrustment.is_delete
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.create_time
     *
     * @return the value of entrustment.create_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.create_time
     *
     * @param create_time the value for entrustment.create_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment.update_time
     *
     * @return the value of entrustment.update_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment.update_time
     *
     * @param update_time the value for entrustment.update_time
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}