package com.smikevon.easy.mbg.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EntrustmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public EntrustmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andApply_typeIsNull() {
            addCriterion("apply_type is null");
            return (Criteria) this;
        }

        public Criteria andApply_typeIsNotNull() {
            addCriterion("apply_type is not null");
            return (Criteria) this;
        }

        public Criteria andApply_typeEqualTo(Integer value) {
            addCriterion("apply_type =", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotEqualTo(Integer value) {
            addCriterion("apply_type <>", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeGreaterThan(Integer value) {
            addCriterion("apply_type >", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_type >=", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeLessThan(Integer value) {
            addCriterion("apply_type <", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeLessThanOrEqualTo(Integer value) {
            addCriterion("apply_type <=", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeIn(List<Integer> values) {
            addCriterion("apply_type in", values, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotIn(List<Integer> values) {
            addCriterion("apply_type not in", values, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeBetween(Integer value1, Integer value2) {
            addCriterion("apply_type between", value1, value2, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_type not between", value1, value2, "apply_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeIsNull() {
            addCriterion("deal_type is null");
            return (Criteria) this;
        }

        public Criteria andDeal_typeIsNotNull() {
            addCriterion("deal_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeal_typeEqualTo(Integer value) {
            addCriterion("deal_type =", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeNotEqualTo(Integer value) {
            addCriterion("deal_type <>", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeGreaterThan(Integer value) {
            addCriterion("deal_type >", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_type >=", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeLessThan(Integer value) {
            addCriterion("deal_type <", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeLessThanOrEqualTo(Integer value) {
            addCriterion("deal_type <=", value, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeIn(List<Integer> values) {
            addCriterion("deal_type in", values, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeNotIn(List<Integer> values) {
            addCriterion("deal_type not in", values, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeBetween(Integer value1, Integer value2) {
            addCriterion("deal_type between", value1, value2, "deal_type");
            return (Criteria) this;
        }

        public Criteria andDeal_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_type not between", value1, value2, "deal_type");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Long value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Long value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Long value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Long value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Long value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Long> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Long> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Long value1, Long value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Long value1, Long value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountIsNull() {
            addCriterion("entrust_amount is null");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountIsNotNull() {
            addCriterion("entrust_amount is not null");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountEqualTo(Integer value) {
            addCriterion("entrust_amount =", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountNotEqualTo(Integer value) {
            addCriterion("entrust_amount <>", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountGreaterThan(Integer value) {
            addCriterion("entrust_amount >", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("entrust_amount >=", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountLessThan(Integer value) {
            addCriterion("entrust_amount <", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountLessThanOrEqualTo(Integer value) {
            addCriterion("entrust_amount <=", value, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountIn(List<Integer> values) {
            addCriterion("entrust_amount in", values, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountNotIn(List<Integer> values) {
            addCriterion("entrust_amount not in", values, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountBetween(Integer value1, Integer value2) {
            addCriterion("entrust_amount between", value1, value2, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andEntrust_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("entrust_amount not between", value1, value2, "entrust_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountIsNull() {
            addCriterion("deal_amount is null");
            return (Criteria) this;
        }

        public Criteria andDeal_amountIsNotNull() {
            addCriterion("deal_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDeal_amountEqualTo(Integer value) {
            addCriterion("deal_amount =", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountNotEqualTo(Integer value) {
            addCriterion("deal_amount <>", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountGreaterThan(Integer value) {
            addCriterion("deal_amount >", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_amount >=", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountLessThan(Integer value) {
            addCriterion("deal_amount <", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountLessThanOrEqualTo(Integer value) {
            addCriterion("deal_amount <=", value, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountIn(List<Integer> values) {
            addCriterion("deal_amount in", values, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountNotIn(List<Integer> values) {
            addCriterion("deal_amount not in", values, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountBetween(Integer value1, Integer value2) {
            addCriterion("deal_amount between", value1, value2, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andDeal_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_amount not between", value1, value2, "deal_amount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrustment
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 16 19:12:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrustment
     *
     * @mbg.generated Thu Aug 16 19:12:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}