#mybatis.type-aliases-package=com.neo.entity

spring :
  datasource :
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/mbg_demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username : root
    password : 123456

## Redis 缓存信息
  redis:
    host: 127.0.0.1
    port: 6379
    #password: battcn
    timeout: 10000
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

mybatis:
  type-aliases-package: com.smikevon.easy.model.entity
  type-handlers-package: com.smikevon.easy.mbg.handler
  mapper-locations: classpath:mappers/**/*.xml
  configuration :
    cacheEnabled : true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql